name: Experiment with Evidently
description: Experiment with Evidently Exercise
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2023-07-31"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    short_summary: Install dependencies
    script: cml/install_dependencies.py
    kernel: python3
    cpu: 1
    memory: 2
